elements:
  - name: Product
    indices:
      - name
      - permalink
      - brand
      - web_shops
      - type
      - status
      - sku
  - name: TestNode
    indices:
      - name
      - age
      - mood
      - tags